### ISSUE TITLE
Feature Request: The ability to declare different screen's side's gaps seperately

### ISSUE THREAD

**Issue by HPsaucii** [areif-dev/river-bsp-layout#1]
Hiya! Just switched over from BSPWM to riverWM, and i stumbled across your project. I really like it for the most part, except for one not-so-tiny thing
basically, currently you can only configure a global outer-gap that applies to all sides, which isnt great
This means that you cant have things like bars (unless im mistaken) without either
1. The bar overlapping your window's, or
2. Having to have a gap on every single side, which for some isnt as aesthetically appealing.
Ideally you'd be able to pass individual arguements for each side of the screen, and it would adjust accordingly

**Comment by areif-dev** [comment]
That's not such a bad idea! I'll see about getting something working.

**Comment by areif-dev** [comment]
I believe I have your concern addressed in [v2.0.0](https://github.com/areif-dev/river-bsp-layout/releases/tag/v2.0.0). Thank you for the suggestion!
